package com.clinicbot.clinic_bot.model;

public enum AppointmentState {
    SELECT_CLINIC,
    SELECT_SPECIALIZATION,
    SELECT_DOCTOR,
    SELECT_DAY,
    SELECT_TIME,
    ENTER_COMPLAINTS,
    CONFIRM_APPOINTMENT,
    MANAGE_DOCTORS,
    ADD_DOCTOR,
    EDIT_DOCTOR,
    DELETE_DOCTOR,
    MANAGE_CLINICS,
    CONFIRMING,
    EDIT_DOCTOR_FULLNAME,
    EDIT_DOCTOR_SPECIALIZATION,
    EDIT_DOCTOR_CLINICS
}
